services:
  postgres:
    image: postgres:16
    container_name: fastapi-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: fastapi_db
    ports:
      - "5432:5432" 

    volumes:
      - postgres_data:/var/lib/postgresql/data  

  fastapi:
    image: fastapi-app:1.0
    container_name: fastapi-app
    ports:
      - "8000:8000"
    depends_on:
      - postgres     

volumes:
  postgres_data:


















  # Ye line sabse important hai
  # volumes:
  # - postgres_data:/var/lib/postgresql/data

  # postgres_data=Docker ka named volume hai.
  # /var/lib/postgresql/data =PostgreSQL container ke andar woh location hai jahan PostgreSQL apna actual database data rakhta hai

#   PostgreSQL
#     ↓
# /var/lib/postgresql/data
#     ↓
# postgres_data volume